### ISSUE TITLE
Feature Request: Allow folding the "block run" starting tag.

### ISSUE THREAD

**Issue by stef-rausch** [HananoshikaYomaru/obsidian-run#5]
The UX can be enhanced further if one could fold the `block run` starting tag `%% run start <id> <expression> ... %%`.

The visual result would be:

~~~
%% run start <id>
Output
%% run end %%
~~~

That looks much neater in edit and source mode, i.e., it would be less disruptive while writing a note.

Look at how the `Fold Anywhere` plugin does it: https://github.com/Quorafind/Obsidian-Fold-Anywhere.

By the way: there are compatibility issues of `Run` with `Fold Anywhere` you might want to look into. 😉

**Comment by HananoshikaYomaru** [comment]
definitely better UX, will look at it

**Comment by HananoshikaYomaru** [comment]
this can be done using https://github.com/mugiwara85/CodeblockCustomizer

<img width="779" alt="CleanShot 2023-10-03 at 09 14 35@2x" src="https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/d278a370-63d6-4dc2-a3f4-68767745ac92">

<img width="760" alt="CleanShot 2023-10-03 at 09 14 44@2x" src="https://github.com/HananoshikaYomaru/obsidian-run/assets/43137033/6ac2a200-d202-43ad-b234-55da122ac84b">

but I need to parse the language code better so that it can read `ts fold`

**Comment by stef-rausch** [comment]
To be frank, I'm not too fond of only folding the code block.

Will installing the `CodeblockCustomizer` be necessary, or are you re-implementing the feature? I would like to avoid having to add another plugin to my active list.

For me, it is clear that when the `run block starting tag` is folded, there is code hidden. I don't need to see that there is a code block visually.

From a textual point of view, it is cleaner (and, for me more appealing) to only see the `start tag`, the output and the `end tag`, as shown in https://github.com/HananoshikaYomaru/obsidian-run/issues/5#issue-1923834950. I would like to minimise the visual clutter. 😉 

My 2 cents.

**Comment by HananoshikaYomaru** [comment]
I see your point. It is possible to do it like  https://github.com/Quorafind/Obsidian-Fold-Anywhere but I will need a whole set of logic just for folding starting tag. It kind of sidetrack the plugin which I don't want to. Now the plugin code is clean and neat. I want to keep it simple. 

I will consider your idea as "possible"
